[package]
name = "lemondb"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/lemondb"
homepage = "https://github.com/al8n/lemondb"
documentation = "https://docs.rs/lemondb"
description = "A template for creating Rust open-source repo on GitHub"
license = "MIT OR Apache-2.0"
rust-version = "1.73"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = ["std"]
alloc = ["hashbrown"]
sync = ["oneshot", "crossbeam-channel"]
std = [
  "ahash/default",
  "bytes/default",
  "crossbeam-skiplist/default",
  "either/default",
  "skl/memmap",
  "thiserror",
  "memmap2",
  "fs4",
  "indexmap/default",
  "atomic_refcell/default",
  "quick_cache",
  "smallvec-wrapper/default",
]

[dependencies]
ahash = { version = "0.8", default-features = false }
atomic_refcell = { version = "0.1", default-features = false }
bytes = { version = "1", default-features = false }
crc32fast = "1"
crossbeam-skiplist = { version = "0.1", default-features = false }
derive_more = "0.99"
enum_dispatch = "0.3"
either = { version = "1", default-features = false }
fs4 = { version = "0.8", optional = true }
hashbrown = { version = "0.14", optional = true }
indexmap = { version = "2", default-features = false }
memmap2 = { version = "0.9", optional = true }
quick_cache = { version = "0.5", optional = true }
skl = { version = "0.8", default-features = false }
smallvec-wrapper = { version = "0.1", default-features = false, features = ["const_new"] }
thiserror = { version = "1", optional = true }
tracing = "0.1"
viewit = "0.1.5"

# sync
oneshot = { version = "0.1", optional = true }
crossbeam-channel = { version = "0.5", optional = true }

# future




[dev-dependencies]
criterion = "0.5"
tempfile = "3"

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
